### ISSUE TITLE
GCC module

### ISSUE THREAD

**Issue by MBirn** [PeriHPX/HPCBuildInfrastructure#7]
While I understand that requiring modules (with specific names) of direct dependencies in the self written module files can help, I would prefer to not have GCC and maybe cmake hardcoded there.

With that `prereq` it is cumbersome to use other custom installations of compilers or the default system compiler.

**Comment by diehlpk** [comment]
@MBirn It is not perfect, but the option `without-gcc` uses the default system gcc and the option with `with-gcc` uses the compiled gcc with the build system.
